In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
dfx = pd.read_csv("C:/Users/ramesh/Desktop/My CB ML/Air Pollution Project/Train.csv")
dfxt = pd.read_csv("C:/Users/ramesh/Desktop/My CB ML/Air Pollution Project/Test.csv")

In [5]:
XTrain = dfx.values

x = XTrain[:,0:5]
y = XTrain[:,5]

xt = dfxt.values

print(XTrain.shape)
print(x.shape)
print(y.shape)
print(xt.shape)

(1600, 6)
(1600, 5)
(1600,)
(400, 5)


In [6]:
X = (x-x.mean())/x.std()
Y = y
print(dfx.head())
print()
print(X)
print()
print(Y)

   feature_1  feature_2  feature_3  feature_4  feature_5     target
0   0.293416  -0.945599  -0.421105   0.406816   0.525662 -82.154667
1  -0.836084  -0.189228  -0.776403  -1.053831   0.597997 -48.897960
2   0.236425   0.132836  -0.147723   0.699854  -0.187364  77.270371
3   0.175312   0.143194  -0.581111  -0.122107  -1.292168  -2.988581
4  -1.693011   0.542712  -2.798729  -0.686723   1.244077 -37.596722

[[ 0.31139642 -0.92093003 -0.3992678   0.42418404  0.5423883 ]
 [-0.81200658 -0.16864243 -0.75264729 -1.02857829  0.61433283]
 [ 0.25471295  0.15168305 -0.12736142  0.71564009 -0.16678861]
 ...
 [ 1.05810433 -0.87478823  1.74062205 -1.84139222  0.45969493]
 [-1.24275748  0.01453923  1.8672047  -1.05496863  0.75192314]
 [-1.85426585 -0.8252779  -1.42486653  0.50553954  1.47126077]]

[ -82.15466656  -48.89796018   77.2703707  ... -107.51050797  -47.34155781
 -115.93900296]


# Algorithm

In [7]:
def hypothesis(x, theta): 
    return theta[0] + theta[1]*x                    # eqn of lime y= c + mx

def error(X, Y, theta):
    
    m = X.shape[0]
    error = 0
    
    for i in range(m):
        hx = hypothesis(X[i], theta)
        error += (hx - Y[i])**2
    return error

# ALgorithm

def gradient(X , Y, theta):                             # to get grad[0] and grad[1]
    
    
    m = X.shape[0]
    grad = np.zeros((m,))
    for i in range(m):
        hx = hypothesis(X[i], theta)
        grad[0] += (hx - Y[i])
        grad[i] += (hx- Y[i])*X[i]
    
    return grad
    
    

def gradientDescent(X ,Y, learning_rate = 0.00001):
    
    theta = np.zeros((2, ))
    
    itr = 0
    max_itr = 300
    error_list = []
    while(itr<= max_itr):
        e = error(X,Y,theta)
        error_list.append(e)
        grad = gradient(X,Y,theta)
        theta[0] = theta[0] - learning_rate*grad[0]
        theta[1] = theta[1] - learning_rate*grad[1]
        itr+=1
        
    return theta, error_list
        

In [8]:
'''def hypothesis(x, theta):
    m = X.shape[0]
    zzz = theta[0]
    for j in range(1,m):
        zzz +=  theta[j]*x                    # eqn of lime y= c + mx

def error(X, Y, theta):
    
    m = X.shape[0]
    error = 0
    
    for i in range(m):
        hx = hypothesis(X[i], theta)
        error += (hx - Y[i])**2
    return error

# ALgorithm

def gradient(X , Y, theta):                              # to get grad[0] and grad[1]
    
    grad = np.zeros((2,))
    m = X.shape[0]
    for i in range(m):
        hx = hypothesis(X[i], theta)
        
        grad[0] += (hx - Y[i])
        grad[i+1] += (hx- Y[i])*X[i]
    
    return grad
    
    

def gradientDescent(X ,Y, learning_rate = 0.00001):
    
    theta = np.zeros((2, ))
    
    m =X.shape[0] 
    
    itr = 0
    max_itr = 300
    error_list = []
    while(itr<= max_itr):
        e = error(X,Y,theta)
        error_list.append(e)
        grad = gradient(X,Y,theta)
        
        z += (hx - Y[i])*X[i]
        for j in range(m):
            
            theta[j] = theta[j] - learning_rate*z
        itr+=1
        
    return theta, error_list
    '''

'def hypothesis(x, theta):\n    m = X.shape[0]\n    zzz = theta[0]\n    for j in range(1,m):\n        zzz +=  theta[j]*x                    # eqn of lime y= c + mx\n\ndef error(X, Y, theta):\n    \n    m = X.shape[0]\n    error = 0\n    \n    for i in range(m):\n        hx = hypothesis(X[i], theta)\n        error += (hx - Y[i])**2\n    return error\n\n# ALgorithm\n\ndef gradient(X , Y, theta):                              # to get grad[0] and grad[1]\n    \n    grad = np.zeros((2,))\n    m = X.shape[0]\n    for i in range(m):\n        hx = hypothesis(X[i], theta)\n        \n        grad[0] += (hx - Y[i])\n        grad[i+1] += (hx- Y[i])*X[i]\n    \n    return grad\n    \n    \n\ndef gradientDescent(X ,Y, learning_rate = 0.00001):\n    \n    theta = np.zeros((2, ))\n    \n    m =X.shape[0] \n    \n    itr = 0\n    max_itr = 300\n    error_list = []\n    while(itr<= max_itr):\n        e = error(X,Y,theta)\n        error_list.append(e)\n        grad = gradient(X,Y,theta)\n        \n      

In [9]:
final_theta, error_list = gradientDescent(X, Y)

ValueError: setting an array element with a sequence.